// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEiT0JhgUF87IGc07gNTCE_eboQH-Ahmc',
    appId: '1:977645765493:web:471d689714ab5efb9c893c',
    messagingSenderId: '977645765493',
    projectId: 'proyek-sangu',
    authDomain: 'proyek-sangu.firebaseapp.com',
    storageBucket: 'proyek-sangu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjYW8o8GmT_mnufMYqBbdagjuCYCh5Yhs',
    appId: '1:977645765493:android:237790e19ca9f7c39c893c',
    messagingSenderId: '977645765493',
    projectId: 'proyek-sangu',
    storageBucket: 'proyek-sangu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN5YHJJ6UttvWQC5qvqTYmBJRRX6vjztw',
    appId: '1:977645765493:ios:bce383fd4e298deb9c893c',
    messagingSenderId: '977645765493',
    projectId: 'proyek-sangu',
    storageBucket: 'proyek-sangu.appspot.com',
    iosBundleId: 'com.mbokmu.sangu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN5YHJJ6UttvWQC5qvqTYmBJRRX6vjztw',
    appId: '1:977645765493:ios:bce383fd4e298deb9c893c',
    messagingSenderId: '977645765493',
    projectId: 'proyek-sangu',
    storageBucket: 'proyek-sangu.appspot.com',
    iosBundleId: 'com.mbokmu.sangu',
  );
}
